// Generated by squad init/upgrade — do not edit
//
// Append-only attestation store for bot-authored GitHub writes.
// Uses only Node.js built-in modules — no npm dependencies required.
//
// Usage:
//   node attestation-store.mjs --record --write-type pr-create --owner org --repo repo ...
//   node attestation-store.mjs --list [--date 20250429] [--role-slug backend] [--actor-match true]
//   node attestation-store.mjs --verify --attestation-id attest_abc123

import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, appendFileSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

// ============================================================================
// Helpers
// ============================================================================

/** YYYYMMDD in UTC for the given unix timestamp (seconds), or today. */
function dateStamp(unixSeconds) {
  const d = unixSeconds ? new Date(unixSeconds * 1000) : new Date();
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const day = String(d.getUTCDate()).padStart(2, '0');
  return `${y}${m}${day}`;
}

function generateAttestationId() {
  return `attest_${randomBytes(8).toString('hex')}`;
}

// ============================================================================
// Public API
// ============================================================================

/**
 * Returns the path to the JSONL log file for a given date.
 * @param {string} attestationDir  Absolute or relative directory path.
 * @param {string} [date]          YYYYMMDD string; defaults to today (UTC).
 */
export function getLogPath(attestationDir, date) {
  return join(attestationDir, `log-${date ?? dateStamp()}.jsonl`);
}

/**
 * Append a single attestation record to the daily log.
 * Creates the attestation directory if it does not exist.
 */
export function recordAttestation({
  writeType,
  owner,
  repo,
  targetObject,
  roleSlug,
  scopeId,
  expectedActor,
  actualActor,
  writeId,
  timestampUnix,
  attestationDir = '.squad/attestation',
}) {
  mkdirSync(attestationDir, { recursive: true });

  const ts = timestampUnix ?? Math.floor(Date.now() / 1000);
  const actorMatch = expectedActor === actualActor;
  const record = {
    attestation_id: generateAttestationId(),
    write_type: writeType,
    timestamp_unix: ts,
    scope_id: scopeId,
    role_slug: roleSlug,
    expected_actor: expectedActor,
    actual_actor: actualActor,
    actor_match: actorMatch,
    owner,
    repo,
    target_object: targetObject,
    write_id: writeId,
  };

  const logPath = getLogPath(attestationDir, dateStamp(ts));
  appendFileSync(logPath, JSON.stringify(record) + '\n', 'utf8');
  return record;
}

/**
 * Read and optionally filter attestation records.
 * When no date is given, reads today's log.
 */
export function listAttestations({
  attestationDir = '.squad/attestation',
  date,
  roleSlug,
  actorMatch,
} = {}) {
  const logPath = getLogPath(attestationDir, date ?? dateStamp());
  if (!existsSync(logPath)) return [];

  const lines = readFileSync(logPath, 'utf8').split('\n').filter(Boolean);
  let records = lines.map((l) => JSON.parse(l));

  if (roleSlug !== undefined) {
    records = records.filter((r) => r.role_slug === roleSlug);
  }
  if (actorMatch !== undefined) {
    const match = typeof actorMatch === 'boolean' ? actorMatch : actorMatch === 'true';
    records = records.filter((r) => r.actor_match === match);
  }

  return records;
}

/**
 * Look up a single attestation by ID across all daily logs in the directory.
 * Returns the record or null.
 */
export function verifyAttestation(attestationId, { attestationDir = '.squad/attestation' } = {}) {
  if (!existsSync(attestationDir)) return null;

  const files = readdirSync(attestationDir)
    .filter((f) => f.startsWith('log-') && f.endsWith('.jsonl'))
    .sort()
    .reverse(); // newest first

  for (const file of files) {
    const lines = readFileSync(join(attestationDir, file), 'utf8').split('\n').filter(Boolean);
    for (const line of lines) {
      const record = JSON.parse(line);
      if (record.attestation_id === attestationId) return record;
    }
  }
  return null;
}

// ============================================================================
// CLI entry point
// ============================================================================

function cli(args) {
  const flag = (name) => {
    const idx = args.indexOf(name);
    if (idx === -1) return undefined;
    return args[idx + 1];
  };
  const has = (name) => args.includes(name);

  const attestationDir = flag('--attestation-dir') ?? '.squad/attestation';

  if (has('--record')) {
    const result = recordAttestation({
      writeType: flag('--write-type'),
      owner: flag('--owner'),
      repo: flag('--repo'),
      targetObject: flag('--target-object'),
      roleSlug: flag('--role-slug'),
      scopeId: flag('--scope-id'),
      expectedActor: flag('--expected-actor'),
      actualActor: flag('--actual-actor'),
      writeId: flag('--write-id'),
      timestampUnix: flag('--timestamp-unix') ? Number(flag('--timestamp-unix')) : undefined,
      attestationDir,
    });
    process.stdout.write(JSON.stringify(result, null, 2) + '\n');
  } else if (has('--list')) {
    const result = listAttestations({
      attestationDir,
      date: flag('--date'),
      roleSlug: flag('--role-slug'),
      actorMatch: flag('--actor-match'),
    });
    process.stdout.write(JSON.stringify(result, null, 2) + '\n');
  } else if (has('--verify')) {
    const id = flag('--attestation-id');
    const result = verifyAttestation(id, { attestationDir });
    process.stdout.write(JSON.stringify(result, null, 2) + '\n');
  } else {
    process.stderr.write('Usage: node attestation-store.mjs --record|--list|--verify [options]\n');
    process.exit(1);
  }
}

// Run CLI when executed directly
const isMain =
  typeof process !== 'undefined' &&
  process.argv[1] &&
  import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/'));

if (isMain) {
  cli(process.argv.slice(2));
}
