#!/usr/bin/env node
// Generated by squad init/upgrade — do not edit
//
// Agent-callable script that exchanges a lease scope_id for the actual token.
// Agents call this instead of resolve-token directly.
//
// Usage: node exchange-lease.mjs --scope-id lease_abc123def456 --role backend
// Output: JSON { token, remainingOps } on stdout (exit 0), or { error } on stderr (exit 1).

import { parseArgs } from 'node:util';
import { exchangeLease } from './token-lease-store.mjs';

// ============================================================================
// Programmatic API
// ============================================================================

/**
 * Exchange a lease for its token.
 * @param {object} opts
 * @param {string} opts.scopeId - Lease identifier.
 * @param {string} opts.role - Expected role slug.
 * @returns {Promise<{ token: string, remainingOps: number }>}
 */
export async function exchange({ scopeId, role }) {
  return exchangeLease(scopeId, role);
}

// ============================================================================
// CLI entry point
// ============================================================================

async function main() {
  const { values } = parseArgs({
    options: {
      'scope-id': { type: 'string' },
      'role': { type: 'string' },
    },
    strict: true,
  });

  const scopeId = values['scope-id'];
  const role = values['role'];

  if (!scopeId) {
    process.stderr.write(JSON.stringify({ error: '--scope-id is required' }) + '\n');
    process.exit(1);
  }
  if (!role) {
    process.stderr.write(JSON.stringify({ error: '--role is required' }) + '\n');
    process.exit(1);
  }

  const result = exchangeLease(scopeId, role);
  process.stdout.write(JSON.stringify(result) + '\n');
}

// Run CLI when executed directly
const isMain = process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/'));
if (isMain) {
  main().catch((err) => {
    process.stderr.write(JSON.stringify({ error: err.message }) + '\n');
    process.exit(1);
  });
}
