#!/usr/bin/env node
// Generated by squad init/upgrade — do not edit
//
// CLI wrapper around the token-lease-store.
// Called by the coordinator agent to create a lease for a spawned agent.
//
// Usage:
//   node token-lease.mjs --role backend --max-ops 5 --max-time 600
//
// Output (stdout): JSON { scopeId, role, deadlineUnix, remainingOps }
// Exit 0 on success, exit 1 with { error: message } on failure.

import { parseArgs } from 'node:util';
import { fileURLToPath } from 'node:url';
import { dirname, resolve as resolvePath } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function fail(message) {
  process.stdout.write(JSON.stringify({ error: message }) + '\n');
  process.exit(1);
}

async function main() {
  const { values } = parseArgs({
    options: {
      role: { type: 'string' },
      'max-ops': { type: 'string', default: '3' },
      'max-time': { type: 'string', default: '300' },
    },
    strict: true,
  });

  const role = values.role;
  if (!role) fail('--role is required');

  const maxOps = parseInt(values['max-ops'], 10);
  const maxTimeSec = parseInt(values['max-time'], 10);

  if (Number.isNaN(maxOps) || maxOps < 1) fail('--max-ops must be a positive integer');
  if (Number.isNaN(maxTimeSec) || maxTimeSec < 1) fail('--max-time must be a positive integer');

  // Dynamic import of resolve-token to handle missing module gracefully
  let resolveToken;
  try {
    const mod = await import(resolvePath(__dirname, 'resolve-token.mjs'));
    resolveToken = mod.resolveToken;
  } catch (err) {
    fail(`Failed to load resolve-token module: ${err.message}`);
  }

  const repoRoot = process.cwd();
  const token = await resolveToken(repoRoot, role);
  if (!token) fail(`Could not resolve token for role '${role}'`);

  const { createLease } = await import(resolvePath(__dirname, 'token-lease-store.mjs'));
  const lease = createLease({ role, token, maxOps, maxTimeSec });

  // Print lease metadata (never the token itself)
  process.stdout.write(JSON.stringify({
    scopeId: lease.scopeId,
    role: lease.role,
    deadlineUnix: lease.deadlineUnix,
    remainingOps: lease.remainingOps,
  }) + '\n');
}

main().catch((err) => fail(err.message));
